site_name: pyjokes
theme: mkdocs
site_url: https://pyjok.es/
repo_url: https://github.com/pyjokes/pyjokes
site_description: One-line programmer jokes (jokes-as-a-service)
site_author: PyJokes Society
site_dir: www
nav:
    - 'Home': 'index.md'
    - 'Install': 'install.md'
    - 'API Reference': 'api.md'
    - 'PyJokes Society': 'society.md'
    - 'Story': 'story.md'
